### ISSUE TITLE
jd_scripts_jd_bean_sign 运行报错

### ISSUE THREAD

**Issue by cytown** [yuannian1112/jd_scripts#15]
最新版本，错误如下：

```
开始执行 京东多合一签到 签到，请稍等...

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/utils/JDJRValidator_Pure.js
- /ql/scripts/utils/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/ql/scripts/utils/JDJRValidator_Pure.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/utils/JDJRValidator_Pure.js',
    '/ql/scripts/utils/JD_DailyBonus.js'
  ]
}
京东签到脚本执行异常:Error: Command failed: /usr/local/bin/node ./utils/JD_DailyBonus.js >> ./result.txt
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/utils/JDJRValidator_Pure.js
- /ql/scripts/utils/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/ql/scripts/utils/JDJRValidator_Pure.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/utils/JDJRValidator_Pure.js',
    '/ql/scripts/utils/JD_DailyBonus.js'
  ]
}

```

**Comment by cytown** [comment]
使用npm install png-js --save 能够解决，但感觉不是正途。
